language: scala
sudo: false
scala:
  - "2.11.6"
jdk:
  - oraclejdk8
branches:
  only:
    - master
before_script:
  - psql -c 'create database docker;' -U postgres
addons:
  postgresql: "9.3"
notifications:
  email:
    - dnvriend@gmail.com